services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fcg-catalog-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Fcg@123456"
    ports:
      - "1433:1433"
    volumes:
      - catalog_sqlserver_data:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: fcg-catalog-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

volumes:
  catalog_sqlserver_data:
